deathCauses:
  BEES:
    - "abejas"
    - "picado"
    - "picadura"
  CACTUS:
    - "cactus"
    - "pinchos"
    - "pinchazo"
  DROWNING:
    - "agua"
    - "ahogado"
    - "ahogamiento"
  FIRE:
    - "fuego"
    - "quemado"
    - "quemadura"
  SUFFOCATION:
    - "sofocado"
    - "sofocamiento"
  LAVA:
    - "lava"
  LIGHTNING:
    - "rayo"
  POISON:
    - "veneno"
    - "envenenado"
    - "envenenamiento"
  EXPLOSION:
    - "explosion"
    - "explosivo"
    - "explosiva"
    - "TNT"
  ARROWS:
    - "flecha"
    - "flechas"
    - "flechazo"
    - "flechado"
    - "flechazos"
  WOLFS:
    - "lobo"
    - "lobos"
    - "perro"
    - "perros"
    - "mordido"
    - "mordida"
    - "mordedura"
    - "rabia"
  GIANT:
    - "gigante"
    - "gigantes"
    - "giant"
names:
  - "Leon"
  - "Rhys"
  - "Ian"
  - "Carson"
  - "Arjun"
  - "Winston"
  - "Jesse"
  - "Cedric"
  - "Zane"
  - "Luciano"
  - "Gerald"
  - "Kevin"
  - "Korbin"
  - "Aryan"
  - "Elliott"
  - "Deven"
  - "Wyatt"
  - "Amare"
  - "Micheal"
  - "Marcel"
  - "Yusuf"
  - "Jon"
  - "Zachariah"
  - "Enrique"
  - "Rishi"
  - "Ray"
  - "Darrell"
  - "Dylan"
  - "Bennett"
  - "Yosef"
  - "Billy"
  - "Dominique"
  - "Desmond"
  - "Braeden"
  - "Deangelo"
  - "Rory"
  - "Brennan"
  - "Aldo"
  - "Darion"
  - "Javier"
  - "Colby"
  - "Rashad"
  - "Sawyer"
  - "Antoine"
  - "Jaxson"
  - "Rocco"
  - "Jamie"
  - "Ross"
  - "Noel"
  - "Tanner"
  - "Max"
  - "Evan"
  - "Gavin"
  - "Zackery"
  - "Lewis"
  - "Zain"
  - "Issac"
  - "Zachery"
  - "Aiden"
  - "Kellen"
  - "Jacob"
  - "Harrison"
  - "Axel"
  - "Santos"
  - "Yurem"
  - "Dallas"
  - "Steve"
  - "Vaughn"
  - "Keith"
  - "Ahmad"
  - "Jayce"
  - "Jose"
  - "Moses"
  - "Cameron"
  - "Isaias"
  - "Isaac"
  - "Johnathan"
  - "Leo"
  - "Trace"
  - "Porter"
  - "Malaki"
  - "Keenan"
  - "Roberto"
  - "Michael"
  - "Avery"
  - "Royce"
  - "Giovanny"
  - "Tyree"
  - "Messiah"
  - "Tomas"
  - "Tristin"
  - "Fernando"
  - "Moshe"
  - "Giovani"
  - "Stanley"
  - "Denzel"
  - "Clay"
  - "Caiden"
  - "Tyler"
  - "Edward"