deathCauses:
  BEES:
    - "abejas"
    - "picado"
    - "picadura"
  CACTUS:
    - "cactus"
    - "pinchos"
    - "pinchazo"
  DROWNING:
    - "agua"
    - "ahogado"
    - "ahogamiento"
  FIRE:
    - "fuego"
    - "quemado"
    - "quemadura"
  SUFFOCATION:
    - "sofocado"
    - "sofocamiento"
  LAVA:
    - "lava"
  LIGHTNING:
    - "rayo"
  POISON:
    - "veneno"
    - "envenenado"
    - "envenenamiento"
  EXPLOSION:
    - "explosion"
    - "explosivo"
    - "explosiva"
    - "TNT"
  ARROWS:
    - "flecha"
    - "flechas"
    - "flechazo"
    - "flechado"
    - "flechazos"
  WOLFS:
    - "lobo"
    - "lobos"
    - "perro"
    - "perros"
    - "mordido"
    - "mordida"
    - "mordedura"
    - "rabia"
  GIANT:
    - "gigante"
    - "gigantes"
    - "giant"
names:
  - "Leon"
  - "Rhys"
  - "Ian"
  - "Carson"
  - "Arjun"
  - "Winston"
  - "Jesse"
  - "Cedric"
  - "Zane"
  - "Luciano"
  - "Gerald"
  - "Kevin"
  - "Korbin"
  - "Aryan"
  - "Elliott"
  - "Deven"
  - "Wyatt"
  - "Amare"
  - "Micheal"
  - "Marcel"
  - "Yusuf"
  - "Jon"
  - "Zachariah"
  - "Enrique"
  - "Rishi"
  - "Ray"
  - "Darrell"
  - "Dylan"
  - "Bennett"
  - "Yosef"
  - "Billy"
  - "Dominique"
  - "Desmond"
  - "Braeden"
  - "Deangelo"
  - "Rory"
  - "Brennan"
  - "Aldo"
  - "Darion"
  - "Javier"
  - "Colby"
  - "Rashad"
  - "Sawyer"
  - "Antoine"
  - "Jaxson"
  - "Rocco"
  - "Jamie"
  - "Ross"
  - "Noel"
  - "Tanner"
  - "Max"
  - "Evan"
  - "Gavin"
  - "Zackery"
  - "Lewis"
  - "Zain"
  - "Issac"
  - "Zachery"
  - "Aiden"
  - "Kellen"
  - "Jacob"
  - "Harrison"
  - "Axel"
  - "Santos"
  - "Yurem"
  - "Dallas"
  - "Steve"
  - "Vaughn"
  - "Keith"
  - "Ahmad"
  - "Jayce"
  - "Jose"
  - "Moses"
  - "Cameron"
  - "Isaias"
  - "Isaac"
  - "Johnathan"
  - "Leo"
  - "Trace"
  - "Porter"
  - "Malaki"
  - "Keenan"
  - "Roberto"
  - "Michael"
  - "Avery"
  - "Royce"
  - "Giovanny"
  - "Tyree"
  - "Messiah"
  - "Tomas"
  - "Tristin"
  - "Fernando"
  - "Moshe"
  - "Giovani"
  - "Stanley"
  - "Denzel"
  - "Clay"
  - "Caiden"
  - "Tyler"
  - "Edward"
shinigami_skin:
  texture: "ewogICJ0aW1lc3RhbXAiIDogMTYzNTEwOTU4OTAxNywKICAicHJvZmlsZUlkIiA6ICI0Mzk0NGU5NWZiNjI0NmJiOGIyYmQ5NDZlNWY5YjhhMCIsCiAgInByb2ZpbGVOYW1lIiA6ICJCbGFja0NvdWxkIiwKICAic2lnbmF0dXJlUmVxdWlyZWQiIDogdHJ1ZSwKICAidGV4dHVyZXMiIDogewogICAgIlNLSU4iIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzhhOTUxNzg2ZGJmMjFlNDhiNzU5N2NkYjQ3ZmVkM2UwNjQ5YjdlZjM2MTg5YTA1YTk4MDYzZDM5YThkYzA0NWQiCiAgICB9CiAgfQp9"
  textureSignature: "Vclnl4drBLYyf2Blh4OEYIjWcqHh+zd1tzuAfVNNnZSXZHaXatd32ulPWliQwCD4Y8O0LBNRq8fR3IqcGr91ehTfDGSWvobHVR1IMqiq+PzgLsmBFVicWowbWBI3keW2MySmggqZ0xL9q8oyz62X1/8riEV5cs9irX+RFgIZz7Nrbe1Lq7ncPuqXxa0anVwb6cydub8vKdTKvtdJibaCypjwLBr1S5Y6E+p6cJs6ke4x0bL2qgNXemZ7lAXQVLnuGLxGGnBE77B1FewQ10vYi0SIA/aRnqfh/EOlK8uziXgvMVR/9wrUVGrvF6AAeSuXg/4u1juBnHJA8MnI6yRiicRj6D9RQ5to5XB+HbRUaDdrt49BXSX0jhuBPcIY90kaNLYfjlN0jAu3cWGJ5/LRRKEpwjSwWfcAN1X9NLxnVV8L69ZjaL3RmEyXm9tTCeXORq13EoTR6vj/ZDtYTfIMy1uhNdpJ+q1EFDEQc+6iome296Yo+C7TGZEDpr5an0gSSvumPYppMnUWWUAUiFJW4BkPmLG1TXUHHUwwxA64RcwtNorDIQRsVJBsoVUNgfWfK3FggjxzFa4HV7NYQJjwualqtvp5gRby6S/Mitn9Rwra+ffe2Ult4EcMW5JB0pq9nUzwEUkjH2usET6ftV5aVTo4ChqofbTXzewz2mLNq68="